# Generated by Django 4.2.6 on 2023-10-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Materials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material", models.CharField(max_length=100, verbose_name="Material")),
                ("density", models.IntegerField(verbose_name="Densidad")),
                (
                    "young_module",
                    models.BigIntegerField(verbose_name="Módulo de Young"),
                ),
                ("loss_factor", models.FloatField(verbose_name="Factor de perdidas")),
                ("poisson_module", models.FloatField(verbose_name="Módulo de Poisson")),
            ],
        ),
    ]
