# Generated by Django 4.2.6 on 2023-10-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sw_acoustic_iso", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materials",
            name="young_module",
            field=models.FloatField(verbose_name="Módulo de Young"),
        ),
    ]
