# Generated by Django 4.2.6 on 2023-10-23 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sw_acoustic_iso", "0002_alter_materials_young_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimplePanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sw_acoustic_iso.materials",
                    ),
                ),
            ],
        ),
    ]
