# Generated by Django 4.2.6 on 2023-10-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sw_acoustic_iso", "0003_simplepanel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SimplePanel",
            new_name="MaterialsPanel",
        ),
    ]
